/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens;

import javax.swing.ImageIcon;
import models.Movie;

/**
 *
 * @author T-Man
 */
public class Details extends javax.swing.JFrame {

    Movie movie;

    /**
     * Creates new form Interstellar_Details
     */
    public Details(Movie movie) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.movie = movie;
        thumbnail.setIcon(movie.getThumpnail());
        movieName.setText(movie.getTitle());
        movieDisc.setText(movie.getDiscription());
//        System.out.println("title: " + movie.getTitle() + ", desc: " + movie.getDiscription());
//        jTextArea1.setText(movie.getDiscription());
//        JLabel.setText(movie.getTitle());
//        JLabel descriptionLabel = new JLabel(movie.getDiscription());
    }

//    private Details() {
//        initComponents();
//        this.setLocationRelativeTo(null);
//    }
//    public Details(Movie movie) {
//        initComponents();
//        this.setLocationRelativeTo(null);
//        this.movie = movie;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieDisc = new javax.swing.JTextArea();
        thumbnail = new javax.swing.JLabel();
        movieName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 87));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        backBtn.setText("<-");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 50));

        movieDisc.setBackground(new java.awt.Color(255, 204, 87));
        movieDisc.setColumns(20);
        movieDisc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        movieDisc.setLineWrap(true);
        movieDisc.setRows(5);
        movieDisc.setWrapStyleWord(true);
        jScrollPane1.setViewportView(movieDisc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 390, 400));

        thumbnail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgDetail/the martion.png"))); // NOI18N
        jPanel1.add(thumbnail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 460, 790));

        movieName.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jPanel1.add(movieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 330, 50));

        jButton1.setText("21:00");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 100, 80));

        jButton2.setText("00:00");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 100, 80));

        jButton3.setText("18:00");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 100, 80));

        jButton4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton4.setText("BOOK NOW");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 700, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        Home_Screen home = new Home_Screen();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interstellar_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interstellar_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interstellar_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interstellar_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImageIcon img = new ImageIcon("C:\\Users\\T-Man\\Downloads\\MovieTicketReservation_lastUpdate\\MovieTicketReservation\\src\\imgDetail\\imitation game.png");
                Movie interstellar = new Movie("Interstellar", "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", "scientifc", img, 123);
                new Details(interstellar).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea movieDisc;
    private javax.swing.JLabel movieName;
    private javax.swing.JLabel thumbnail;
    // End of variables declaration//GEN-END:variables
}
